site_name: GuimoNotion
site_author: Guillermo Balsera Suárez
site_description: Apuntes en español sobre distintas tecnologías de desarrrollo, desde lenguajes de programación hasta frameworks de frontend y backend.
copyright: Copyright &copy; 2024 - Guillermo Balsera

theme:
  name: material
  language: es
  logo: img/guimonotion.svg
  favicon: img/guimonotion.svg
  features:
    - content.code.copy
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
  font:
    text: Rubik
    code: Roboto Mono
  palette:
    - scheme: default
      primary: cyan
      accent: cyan
      toggle:
        icon: material/brightness-2
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to light mode


nav:
  - Inicio: index.md
  - Lenguajes:
      - Bash Script: languages/bashScript/index.md
      - Kotlin: languages/kotlin/index.md
      - Python: languages/python/index.md
  - Frontend:
      - Angular:
        - Instalación: frameworks/frontend/angular/index.md
        - Componentes: frameworks/frontend/angular/components/index.md
        - Rutas: frameworks/frontend/angular/routes/index.md
      - Electron: frameworks/frontend/electron/index.md
      - Ionic: frameworks/frontend/ionic/index.md
      - MkDocs: frameworks/frontend/mkdocs/index.md
  - BackEnd:
      - PHP-Laravel: frameworks/backend/php-laravel/index.md
      - Spring-Boot: frameworks/backend/spring-boot/index.md
  - Otros:
      - Markdown: others/markdown/index.md
      - Node: others/node/index.md


extra_css:
  - stylesheets/style.css

markdown_extensions:
  - admonition

extra:
  consent:
    title: Cookies
    description: >-
      Usamos cookies para reconocer tus visitas y preferencias repetidas, 
      así como para medir la efectividad de nuestra documentación y si 
      los usuarios encuentran lo que buscan. Con tu consentimiento, 
      nos ayudas a mejorar nuestra documentación.


