site_name: GuimoNotion

theme:
  name: material
  language: es
  logo: img/guimonotion.svg
  favicon: img/guimonotion.svg
  features:
    - content.code.copy
  font:
    code: Roboto Mono
    text: Roboto Mono
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-2
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

nav:
  - Inicio: README.md
  - Markdown: markdown/README.md
  - MkDocs: mkdocs/README.md
  - Frameworks:
      - FrontEnd:
        - Angular: frameworks/Angular/README.md
        - Electron: frameworks/Electron/README.md
        - Ionic: frameworks/Ionic/README.md
      - BackEnd:
        - PHP-Laravel: frameworks/PHP-Laravel/README.md
        - Spring-Boot: frameworks/Spring-Boot/README.md
  - Lenguajes de programación:
      - Bash Script: languages/bashScript/README.md
      - Kotlin: languages/Kotlin/README.md
      - Python: languages/Python/README.md


extra_css:
  - stylesheets/style.css

copyright: >
  Copyright &copy; 2024 - Guillermo Balsera
