site_name: GuimoNotion

theme:
  name: material
  language: es
  logo: img/guimonotion.svg
  favicon: img/guimonotion.svg
  features:
    - content.code.copy
  font:
    code: Roboto Mono
    text: Roboto Mono
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-2
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

nav:
  - Inicio: index.md
  - Markdown: markdown/index.md
  - MkDocs: mkdocs/index.md
  - Frameworks:
      - FrontEnd:
        - Angular: frameworks/FrontEnd/Angular/index.md
        - Electron: frameworks/FrontEnd/Electron/index.md
        - Ionic: frameworks/FrontEnd/Ionic/index.md
      - BackEnd:
        - PHP-Laravel: frameworks/PHP-Laravel/index.md
        - Spring-Boot: frameworks/Spring-Boot/index.md
  - Lenguajes de programación:
      - Bash Script: languages/bashScript/index.md
      - Kotlin: languages/Kotlin/index.md
      - Python: languages/Python/index.md


extra_css:
  - stylesheets/style.css

copyright: >
  Copyright &copy; 2024 - Guillermo Balsera
