site_name: GuimoNotion
repo_url: https://github.com/guillermoBalsera/Apuntes

theme:
  name: material
  language: es
  logo: img/guimonotion.svg
  favicon: img/guimonotion.svg
  features:
    - content.code.copy
  font:
    code: Roboto Mono
    text: Roboto Mono
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-2
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

nav:
  - Inicio: index.md
  - Frameworks:
      - Frontend:
        - Angular: frameworks/frontend/angular/index.md
        - Angular2: frameworks/frontend/angular2/index.md
        - Electron: frameworks/frontend/electron/index.md
        - Ionic: frameworks/frontend/ionic/index.md
        - MkDocs: frameworks/frontend/mkdocs/index.md
      - BackEnd:
        - PHP-Laravel: frameworks/backend/php-laravel/index.md
        - Spring-Boot: frameworks/backend/spring-boot/index.md
  - Lenguajes de programación:
      - Bash Script: languages/bashScript/index.md
      - Kotlin: languages/kotlin/index.md
      - Python: languages/python/index.md
  - Otros:
    - Markdown: others/markdown/index.md
    - Node: others/node/index.md


extra_css:
  - stylesheets/style.css

#copyright: >
#  Copyright &copy; 2024 - Guillermo Balsera
